---

- hosts: server1
  become: true
  pre_tasks:

  - name: install apache
    tags: apache, server1
    package:
      name:
        - "{{ apache_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: server2
  become: true
  tasks:
  
  - name: install php
    tags: php, server2
    package:
      name:
        - "{{ php_package }}"
      state: latest
      update_cache: yes


